import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from '@/app/ui/nav'
import CollapsibleNavBar from '@/app/ui/mobileNav'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Desktop Navbar */}
        <div className="hidden md:block">
          <NavBar />
        </div>

        {/* Mobile Collapsible Navbar */}
        <div className="block md:hidden">
          <CollapsibleNavBar />
        </div>

        {children}
      </body>
    </html>
  );
}
